# Generated by Django 5.2 on 2025-04-14 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('classroom', '0002_classroom_capacity_alter_block_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='classroom.classroom'),
        ),
    ]
